# Generated by Django 5.1.6 on 2025-02-21 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dev',
            name='confirm_password',
        ),
        migrations.AlterField(
            model_name='dev',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rep_dev.roles'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('opciones', models.ManyToManyField(related_name='menus', to='rep_dev.opcion')),
            ],
        ),
        migrations.CreateModel(
            name='DevDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_dev.descripcion')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripciones', to='rep_dev.dev')),
            ],
            options={
                'unique_together': {('dev', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='DevOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='rep_dev.dev')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_dev.opcion')),
            ],
            options={
                'unique_together': {('dev', 'opcion')},
            },
        ),
    ]
