# Generated by Django 5.1.6 on 2025-02-16 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0002_remove_dev_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_opcion', models.CharField(max_length=100, unique=True)),
                ('ruta_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_dev.accesos')),
            ],
        ),
    ]
