# Generated by Django 5.1.6 on 2025-02-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0002_descripcion_opcion_remove_dev_confirm_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='roles',
            field=models.ForeignKey(default='Vista Cliente', on_delete=django.db.models.deletion.SET_DEFAULT, to='rep_dev.roles'),
        ),
    ]
