# Generated by Django 5.1.6 on 2025-02-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0003_imenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMenu',
        ),
    ]
