# Generated by Django 5.1.6 on 2025-02-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0004_alter_dev_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='clase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
