# Generated by Django 5.1.6 on 2025-02-21 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0005_opcion_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='descripcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='rep_dev.descripcion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DevDescripcion',
        ),
    ]
