# Generated by Django 5.1.6 on 2025-02-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0005_menuitems_menucarga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuCarga',
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
    ]
