# Generated by Django 5.1.6 on 2025-02-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0007_menuitems_menucarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='data',
            field=models.TextField(),
        ),
    ]
