# Generated by Django 5.1.6 on 2025-03-07 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0007_alter_dev_email_alter_dev_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dev',
            name='roles',
            field=models.ForeignKey(default='Admin Dev', on_delete=django.db.models.deletion.SET_DEFAULT, to='rep_dev.roles'),
        ),
        migrations.AlterField(
            model_name='dev',
            name='vistapl',
            field=models.ForeignKey(default='rep_dev/ds_rep_dev/index_ds_dev.html', on_delete=django.db.models.deletion.SET_DEFAULT, to='rep_dev.accesos'),
        ),
    ]
