# Generated by Django 5.1.6 on 2025-03-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0008_alter_dev_roles_alter_dev_vistapl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametech', models.CharField(max_length=100, unique=True)),
                ('imgtech', models.ImageField(upload_to='tech_images/')),
                ('classct', models.CharField(default='content-tech', max_length=100)),
                ('classit', models.CharField(default='img-tech', max_length=100)),
            ],
        ),
    ]
