# Generated by Django 5.1.6 on 2025-02-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0008_alter_menuitems_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
