# Generated by Django 5.1.6 on 2025-02-17 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0009_alter_menuitems_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botonclase', models.CharField(max_length=100)),
                ('textboton', models.CharField(max_length=100)),
                ('imgboton', models.ImageField(upload_to='botones/')),
                ('altimg', models.CharField(max_length=100)),
                ('classimg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArticle', models.CharField(max_length=100)),
                ('iOpcion', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='articulos/')),
                ('desImagen', models.CharField(max_length=100)),
                ('descripcionArticle', models.TextField()),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rep_dev.menuitems')),
                ('boton', models.ManyToManyField(to='rep_dev.botones')),
            ],
        ),
    ]
