# Generated by Django 5.1.6 on 2025-03-07 03:11

import rep_dev.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0009_contech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contech',
            name='imgtech',
            field=models.ImageField(upload_to=rep_dev.models.get_unique_image_path),
        ),
    ]
