# Generated by Django 5.1.6 on 2025-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0010_botones_articulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='iOpcion',
        ),
        migrations.AlterField(
            model_name='botones',
            name='classimg',
            field=models.CharField(default='icon-documentacion', max_length=100),
        ),
    ]
