# Generated by Django 5.1.6 on 2025-03-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0010_alter_contech_imgtech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contech',
            name='classct',
            field=models.CharField(default='content-tech hidden', max_length=100),
        ),
    ]
