# Generated by Django 5.1.6 on 2025-02-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0011_remove_articulos_iopcion_alter_botones_classimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='descArticle',
            field=models.CharField(default='texto-repositorio', max_length=100),
            preserve_default=False,
        ),
    ]
