# Generated by Django 5.1.6 on 2025-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0012_articulos_descarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='desImagen',
            field=models.TextField(),
        ),
    ]
