# Generated by Django 5.1.6 on 2025-02-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0013_alter_articulos_desimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='desImagen',
            field=models.CharField(max_length=100),
        ),
    ]
