# Generated by Django 5.1.6 on 2025-02-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rep_dev', '0014_alter_articulos_desimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='boton',
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='data',
        ),
        migrations.RemoveField(
            model_name='menucarga',
            name='dev',
        ),
        migrations.RemoveField(
            model_name='menucarga',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Botones',
        ),
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='MenuCarga',
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
    ]
